-- SQL Schema for Easy Cafe Application
-- Paste this into the "SQL Editor" in your Supabase Dashboard

-- 1. Create Categories Table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Products Table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price FLOAT8 NOT NULL,
    image_url TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    roasted_level TEXT DEFAULT 'Medium Roasted',
    rating FLOAT8 DEFAULT 4.5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Profiles Table (Linked to Auth)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Enable Row Level Security (RLS)
-- To allow the app to read data without complex rules for now:
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Allow anyone to read menu, users can only read their own profile)
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);

-- 6. Trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 7. Insert Dummy Data (Categories)
INSERT INTO public.categories (name) VALUES 
('Cappuccino'), 
('Espresso'), 
('Latte'), 
('Flat White');

-- 8. Insert Dummy Data (Products)
-- Replace image_urls with actual coffee images later
INSERT INTO public.products (name, description, price, image_url, category_id, roasted_level, rating) VALUES 
('Classic Cappuccino', 'A smooth blend of espresso and steamed milk.', 4.20, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500', 1, 'Medium Roasted', 4.8),
('Strong Espresso', 'Double shot of our finest beans.', 3.14, 'https://images.unsplash.com/photo-1510707577719-af7c185a5bb3?w=500', 2, 'Dark Roasted', 4.5),
('Caramel Latte', 'Sweet caramel syrup with rich espresso.', 5.50, 'https://images.unsplash.com/photo-1593444209783-cd8ffeb03692?w=500', 3, 'Light Roasted', 4.7);
